#!/usr/bin/php -c /etc/php.ini

<?php
# Build an array of services, and how to fixes
$resolutions = array('C:\ Drive Space' => 'You should log into your server, and see if you can clean anything off the C drive.',
                     'D:\ Drive Space' => 'You should log into your server, and see if you can clean anything off the D drive.',
                     'E:\ Drive Space' => 'You should log into your server, and see if you can clean anything off the E drive.',
                     'CPU Load' => 'You should log into your server, and see if there are any programs or services which are out of control.',
                     'Memory Usage' => 'You should log into your server, and see if there are any programs or services which are out of control.',
                     'Service: Firewall' => 'You should log into your server, and make sure the Windows Firewall service is running.',
                     'Service: Adobe Updater' => 'You should log into your server, and make sure the Adobe Updater service is running.'
);

# Get the inputs from the Nagios service
 array_shift($argv); 
 $NotifyType =array_shift($argv);  /*1*/
 $HostName =array_shift($argv);    /*2*/
 $HostAlias =array_shift($argv);   /*3*/
 $HostState =array_shift($argv);    /*4*/
 $HostAddress =array_shift($argv);   /*5*/
 $ServiceOutput =array_shift($argv);   /*6*/
 $DateTime =array_shift($argv);     /*7*/
 $ServiceDescription  =array_shift($argv);    /*8*/
 $ServiceState  =array_shift($argv);   /*9*/
 $To  =array_shift($argv);           /*10*/
 $Duration = round((array_shift($argv))/60,2);   /*11*/
 $ExecTime =array_shift($argv);       /*12*/
 $Totwarnings =array_shift($argv);     /*13*/
 $Totcritical =array_shift($argv);      /*14*/
 $Totunknowns =array_shift($argv);     /*15*/
 $LastServiceOK = array_shift($argv);    /*16*/
 $LastServiceWarning = array_shift($argv);     /*17*/
 $Attempts= array_shift($argv);     /*18*/
 
 $f_downwarn = $Duration;
 $f_color="#dddddd";
 if($ServiceState=="WARNING") {$f_color="#f48400";}
 if($ServiceState=="CRITICAL") {$f_color="#f40000";}
 if($ServiceState=="OK") {$f_color="#00b71a";}
 if($ServiceState=="UNKNOWN") {$f_color="#cc00de";}

 // Check If File Exists ###########
 if($NotifyType=="PROBLEM")
 {
  $currenttime = time();
  $file_name = "/tmp/$HostName.$ServiceDescription.txt";
  if ($Attempts==1)
   {
     if(file_exists($file_name)==true) {unlink($file_name);}
     $currenttime = $currenttime+round(($Duration * 60),0);
     file_put_contents($file_name, "$currenttime");
   }
 }

 if($NotifyType=="RECOVERY")
 {
  $currenttime = time();
  $oldtime = time();
  $file_name = "/tmp/$HostName.$ServiceDescription.txt";
  if (file_exists($file_name)==true)
   {
     $oldtime = intval(file_get_contents($file_name));
   }
   $f_downwarn = round(($currenttime - $oldtime)/60,2);
 }


 $ServiceOutput = str_replace("(","/",$ServiceOutput);
 $ServiceOutput = str_replace(")","/",$ServiceOutput);
 $ServiceOutput = str_replace("[","/",$ServiceOutput);
 $ServiceOutput = str_replace("]","/",$ServiceOutput);


 $subject = "$NotifyType Service: $HostName/$ServiceDescription [$ServiceState]";
 
 $from  ="windowsteam@emich.edu";
 $body = "<html><body><h2 style='color: #006600'>Eastern Michigan University - Division of IT - Windows Systems Team: Service Report Details</h2><br><table border=0 width='98%' cellpadding=0 cellspacing=0><tr><td valign='top'>\r\n";
 $body .= "<table border=0 cellpadding=0 cellspacing=0 width='97%'>";
 $body .= "<tr bgcolor=$f_color><td width='140'><b><font color=#ffffff>Notification:</font></b></td><td><font ";
 $body .= "color=#ffffff><b>$NotifyType [$ServiceState]</b></font></td></tr>\r\n";
 $body .= "<tr bgcolor=#eeeeee><td><b>Service:</b></td><td><font color=#0000CC><b>$ServiceDescription</b></font></td></tr>\r\n";
 $body .= "<tr bgcolor=#fefefe><td><b>Server:</b></td><td><font color=#005500><b>$HostAlias</b></font></td></tr>\r\n";
 $body .= "<tr bgcolor=#eeeeee><td><b>Address:</b></td><td><font color=#005555><b>$HostAddress</b></font></td></tr>\r\n";
 $body .= "<tr bgcolor=#fefefe><td><b>Date/Time:</b></td><td><font color=#005555>$DateTime</font></td></tr>\r\n";
 $body .= "<tr bgcolor=#fefefe><td><b>Additional Info:</b></td><td>$ServiceOutput</td></tr>\r\n";
 $body .= "<tr bgcolor=#eeeeee><td><b>State Duration:</b></td><td><font color=#CC0000><b>$Duration</b> mins.</font></td></tr> \r\n";
 $body .= "<tr bgcolor=#fefefe><td><b>Service ExecTime:</b></td><td><font color=#CC0000><b>$ExecTime</b></font></td></tr></table>\r\n";
 $body .= "</td><td valign='top'><table border=0 cellpadding=0 cellspacing=0 width=250><tr bgcolor=#000055><td><b> \r\n";
 $body .= "<font color=#FFFFFF>Summary</font></b></td><td>.</td></tr> \r\n";
 $body .= "<tr bgcolor=#f6f6ff><td>Total Service Warnings: </td><td> $Totwarnings</td></tr>\r\n";
 $body .= "<tr bgcolor=#fffef6><td>Total Service Critical: </td><td> $Totcritical</td></tr>\r\n";
 $body .= "<tr bgcolor=#f6f6ff><td>Total Service Unknowns: </td><td> $Totunknowns</td></tr>\r\n";
 $body .= "<tr bgcolor=#fffef6><td>Service <i>DOWN</i> For: </td><td> $f_downwarn<i>m</i></td></tr>\r\n";
 $body .= "</table><br/></td></tr></table><br/>\r\n";
 $body .= "<h3>Why Am I Getting This Notification?</h3>";
 $body .= "You are getting this notification because you have been identified as a contact for this server/service, either personally, or because you belong to a team that was listed.<br/><br> \r\n";
 $body .= "<h3>What Should I Do?</h3>";
 if (array_key_exists($ServiceDescription, $resolutions)) {
 $body .= $resolutions[$ServiceDescription];
 $body .= '  If you need assistance, or have questions, please email the Windows Team at windowsteam@emich.edu<br>';
 } else {
 $body .= "The IT Windows Team will reach out to you for further instructions.  If you do anything on this server before then, please notify them at windowsteam@emich.edu to avoid any duplication of efforts.<br/><br> \r\n";
 }
 $body .= "<br/> \r\n";
 $body .= "</body></html> \r\n";
 
 $headers  = "From: $from\r\n";
 $headers .= "Content-type: text/html\r\n"; 

 /* Send eMail Now... */
 $m_true = mail($To, $subject, $body, $headers);
 echo $m_true;


?>


