#!/usr/bin/php -c /etc/php.ini

<?php
/**
 * Created by PhpStorm.
 * User: bpeters
 * Date: 2/3/2016
 * Time: 9:15 AM
 */

########################################################
#
#
#
#
#  THIS IS NOT USED.  Edit "nagios_service_mail" instead!
#
#
#
#
#
#########################################################

# Get the variables passed to this system
$HostName = $argv[1];
$HostIP = $argv[2];
$NotificationType = $argv[3];
$HostState = $argv[4];
$ServiceOutput = $argv[5];
$Time = $argv[6];
$Contacts = $argv[7];
$ServiceDescription = $argv[8];
$ServiceState = $argv[9];

# Get the server information
$Connection = new LansweeperDB();
$Details = $Connection->getServersDetailsByName($HostName);
$Contacts = "Primary OS: " . $Details['Primary OS Contact'] . ", Secondary OS: " . $Details['Secondary OS Contact'] . ", Primary App: " . $Details['Custom03'] . ", Secondary App: " . $Details['Custom04'];

# Create formatting arrays
$BadNotifications = array('PROBLEM', 'FLAPPINGSTART');
$GoodNotifications = array('RECOVERY', 'FLAPPINGSTOP');

# Format colors and such
if (in_array($NotificationType, $BadNotifications)) {
    $NotificationColor = '#CC0000';
} else if (in_array($NotificationType, $GoodNotifications)) {
    $NotificationColor = '#007700';
} else {
    $NotificationColor = '#007700';
}

# Build the email
$subject = "$NotificationType On Server: $HostName For Service: $ServiceDescription";

$from  ="windowsteam@emich.edu";
$body = "<html>
            <body>
                <h3 style='color: #006600'>Eastern Michigan University - Division of IT: Service Report Details</h3>
                <p style='background-color: #ffffcc'><b>Notification Type: </b> <font color=$NotificationColor>$NotificationType</font><br/> \r\n
                <b>Host: </b> <font color=#3333ff>$HostName</font> </br> \r\n
                <b>Address: </b> <font color=#3333ff>$HostIP</font><br/> \r\n
                <b>Service: </b> <font color=#3333ff>$ServiceDescription</font> </br> \r\n
                <b>Service State: </b> <font color=#3333ff>$ServiceState</font> </br> \r\n
                <b>Date/Time: </b><font color=#3333ff>$Time</font><br/><br> \r\n
                <b>Additional Info: </b>$ServiceOutput<br/> \r\n
                <b>View In Nagios: </b><a href='https://winmon.emich.edu/nagios/cgi-bin/extinfo.cgi?type=1&host=$HostName'><b>$HostName</b></a></p><br/><br> \r\n
                <b>Why Am I Getting This Notification?</b><br>\r\n
                You are getting this notification because you have been identified as a contact for this server/service, either personally, or because you belong to a team that was listed.<br/><br> \r\n
                <b>What Should I Do?</b><br>\r\n
                The IT Windows Team will reach out to you for further instructions.  If you do anything on this server before then, please notify them at windowsteam@emich.edu to avoid any duplication of efforts.<br/><br> \r\n
                <br/> \r\n                
                <b>Who Are The Contacts For This Server??</b><br>\r\n
                $Contacts<br> \r\n
                <br/> \r\n
            </body>
        </html> \r\n";

$headers = "From: $from\r\n";
$headers = $headers."Content-type: text/html\r\n";

# Send eMail Now...
mail($f_to, $subject, $body, $headers);


?>

