#!/usr/bin/php -c /etc/php.ini

<?php
 
 array_shift($argv);
 $NotificationType =array_shift($argv);
 $HostName =array_shift($argv);
 $HostAlias =array_shift($argv);
 $HostState =array_shift($argv);
 $HostAddress =array_shift($argv);
 $HostOutput =array_shift($argv);
 $DateTime =array_shift($argv);
 $ServiceDescription  =array_shift($argv);
 $ServiceState  =array_shift($argv);
 $To  =array_shift($argv);
 $Totalup  =array_shift($argv);
 $Totaldown=array_shift($argv); 

 $subject = "$NotificationType Service: $HostName";
 
 $from  ="windowsteam@emich.edu";
 $body = "<html><body><h2 style='color: #006600'>Eastern Michigan University - Division of IT - Windows Systems Team: Host Report Details</h2><br><b>Notification: </b> <font color=#CC0000>$NotificationType</font><br/> \r\n";
 $body .= "<b>Host: </b> <font color=#007700>$HostAlias</font> </br> \r\n";
 $body .= "<b>Address: </b> <font color=#005555>$HostAddress</font><br/> \r\n";
 $body .= "<b>Date/Time: </b><font color=#005555>$DateTime</font><br/> \r\n";
 $body .= "<b>Additional Info: </b>$HostOutput<br/> \r\n";
 $body .= "<b>Total Servers Up: </b>$Totalup<br/>";
 $body .= "<b>Total Servers Down: </b>$Totaldown<br/> \r\n";
 $body .= "<br> \r\n";
 $body .= "<h3>Why Am I Getting This Notification?</h3>";
 $body .= "You are getting this notification because you have been identified as a contact for this server/service, either personally, or because you belong to a team that was listed.<br/><br> \r\n";
 $body .= "<h3>What Should I Do?</h3>";
 $body .= "The IT Windows Team will reach out to you for further instructions.  If you do anything on this server before then, please notify them at windowsteam@emich.edu to avoid any duplication of efforts.<br/><br> \r\n";
 $body .= "<br/> \r\n";
 $body .= "</body></html> \r\n";
 
 $headers = "From: $from\r\n";
 $headers = $headers."Content-type: text/html\r\n"; 

 /* Send eMail Now... */
 mail($To, $subject, $body, $headers);



?>


